### ISSUE TITLE
AttributeError: 'Functional' object has no attribute '_make_predict_function'

### ISSUE THREAD

**Issue by initialkommit** [haven-jeon/PyKoSpacing#12]
# environment
- macOS 10.15.5
- python 3.7
- tensorflow 2.3.0
- keras 2.4.3

I got an error message like below when I tried to install PyKoSpacing.
I guess this error is related to tensorflow/keras version.
Should I install lower version that requirements tells(tensorflow==1.4, keras=2.1)?
Could you please help me out to solve this problem!?

```
Collecting git+https://github.com/haven-jeon/PyKoSpacing.git
  Cloning https://github.com/haven-jeon/PyKoSpacing.git to /private/var/folders/t8/gk_w0m817gb98bq54z5pl_8h0000gn/T/pip-req-build-xy6xtc45
  Running command git clone -q https://github.com/haven-jeon/PyKoSpacing.git /private/var/folders/t8/gk_w0m817gb98bq54z5pl_8h0000gn/T/pip-req-build-xy6xtc45
    ERROR: Command errored out with exit status 1:
     command: /Users/bright/.virtualenvs/test-pykospacing/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/t8/gk_w0m817gb98bq54z5pl_8h0000gn/T/pip-req-build-xy6xtc45/setup.py'"'"'; __file__='"'"'/private/var/folders/t8/gk_w0m817gb98bq54z5pl_8h0000gn/T/pip-req-build-xy6xtc45/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/t8/gk_w0m817gb98bq54z5pl_8h0000gn/T/pip-pip-egg-info-ums9j1or
         cwd: /private/var/folders/t8/gk_w0m817gb98bq54z5pl_8h0000gn/T/pip-req-build-xy6xtc45/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/t8/gk_w0m817gb98bq54z5pl_8h0000gn/T/pip-req-build-xy6xtc45/setup.py", line 2, in <module>
        from pykospacing import __version__
      File "/private/var/folders/t8/gk_w0m817gb98bq54z5pl_8h0000gn/T/pip-req-build-xy6xtc45/pykospacing/__init__.py", line 1, in <module>
        from pykospacing.kospacing import *
      File "/private/var/folders/t8/gk_w0m817gb98bq54z5pl_8h0000gn/T/pip-req-build-xy6xtc45/pykospacing/kospacing.py", line 17, in <module>
        model._make_predict_function()
    AttributeError: 'Functional' object has no attribute '_make_predict_function'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

**Comment by initialkommit** [comment]
https://github.com/haven-jeon/PyKoSpacing/issues/8
관련 이슈

**Comment by haven-jeon** [comment]
Unfortunately, if the version of the trained model does not match, it will not work at this time. However, if we can do some model operator version conversion work, we expect it to work on higher versions.

**Comment by haven-jeon** [comment]
1ab6240e8cb953d2f550da80d8cc9b5a3e0d4c9f

**Comment by haven-jeon** [comment]
c9abc54aa0c1f5fe48eb6f521ec71bea807c1636

**Comment by haven-jeon** [comment]
3.7에서 해당 버전으로 확인 부탁드립니다.

**Comment by haven-jeon** [comment]
제 맥 머신과 CentOS에서는 잘 동작하네요.. ^^ 
확인 후 이슈 클로즈 부탁드립니다.
